### PR TITLE
fix for "Unexpected token )" issue in 1.0.4

### PR DESCRIPTION
**Pull request by anjsudh**

### CODE REVIEW

**Comment by ztotta** [comment]
thanks for fixing this!

**Comment by AiNoKame** [comment]
+1 !

**Comment by RenBean** [comment]
Thank you for displaying the file fix. I thought that comma might have been the issue.

**Comment by tilmankamp** [comment]
Hope it'll get merged soon. Had to downgrade/freeze to 1.0.3 because of this.

**Comment by furixturi** [comment]
Thxxx for the fix! 
I really hope the code owner merges it soon since it's breaking other npm modules which use this one. (Find myself changing their package.json to fix the version to 1.0.3 then do a ```npm install``` manually...)

**Comment by mantoni** [comment]
If you're like me and don't want to wait, `read` is a good alternative: https://www.npmjs.com/package/read

**Pull request merged**
